package com.example.astra

fun countryFlag(code: String): String = when (code) {
    "RU" -> "🇷🇺"
    "US" -> "🇺🇸"
    "GB" -> "🇬🇧"
    "FR" -> "🇫🇷"
    "DE" -> "🇩🇪"
    "IT" -> "🇮🇹"
    "ES" -> "🇪🇸"
    "CA" -> "🇨🇦"
    "AE" -> "🇦🇪"
    "JP" -> "🇯🇵"
    "KR" -> "🇰🇷"
    "CN" -> "🇨🇳"
    "AU" -> "🇦🇺"
    "SG" -> "🇸🇬"
    "TR" -> "🇹🇷"
    "PL" -> "🇵🇱"
    "CZ" -> "🇨🇿"
    "AT" -> "🇦🇹"
    "HU" -> "🇭🇺"
    "NL" -> "🇳🇱"
    "BE" -> "🇧🇪"
    "CH" -> "🇨🇭"
    "NO" -> "🇳🇴"
    "FI" -> "🇫🇮"
    "SE" -> "🇸🇪"
    else -> "🌍"
}